<?php
$ ="Kaydol"] = "Kayıt Ol";
$ ="Giriş Yap"] = "";
$ ="Restoran Kaydı"] = "";
$ ='Giriş Başarılı'] = '';
$ ='Kullanıcı adı veya şifre geçersiz.'] = "";
$ ="kullanıcı adı ve şifre gereklidir"] = "";
$ ="Üzgünüz, kayıtlarımızda kayıtlı olan e-posta adresini girdiniz."] = "";
$ ="HATA: Paket kimliği eksik"] = "";
$ ="HATA: Paket bilgisi bulunamadı"] = "";
$ ="Satıcı Kullanıcı Adı zaten alınmış"] = "";
$ ="Satıcı güncellendi."] = "";
$ ="HATA: güncellenemez"] = "";
$ ="Düzenle"] = "";
$ ="Sil"] = "";
$ ="Eksik parametreler"] = "";
$ ="Başarıyla kaldır."] = "";
$ ="HATA: sorgu yürütülemiyor."] = "";
$ ="Başarıyla Silindi."] = "";
$ ="HATA: sorgu yürütülemiyor."] = "";
$ ="Giriş Başarılı"] = "";
$ ="Giriş Başarısız. Hesap durumunuz"] = "";
$ ="Kullanıcı adı veya şifre geçersiz."] = "";
$ ="Yükleme klasörü oluşturulamıyor. Lütfen yükleme klasörünü 777 iznine sahip ana dizininizde manuel olarak oluşturun."] = "";
$ ="Yükleme Tamamlandı"] = "";
$ ="Dosya boş"] = "";
$ ="Kategori güncellendi."] = "";
$ ="Kategori eklendi."] = "";
$ ="ERROR. veri eklenemiyor."] = "";
$ ="Alt Kategori güncellendi."] = "";
$ ="Alt Kategori eklendi."] = "";
$ ="AddOn Öğe güncellendi."] = "";
$ ="AddOn Öğe eklendi."] = "";
$ ="Boyut güncellendi."] = "";
$ ="Boyut eklendi."] = "";
$ ="Pişirme Ref. güncellendi."] = "";
$ ="Pişirme Referans eklendi."] = "";
$ ="Üzgünüm ama yiyecek ekleme limitine ulaştınız. Lütfen üyeliğinizi yükseltin"] = "";
$ ="Öğe güncellendi."] = "";
$ ="Öğe eklendi."] = "";
$ ="Ayarlar kaydedildi."] = "";
$ ="Sıralama kaydedildi."] = "";
$ ="Mutfak"] = "";
$ ="Mesafe"] = "";
$ ="mil"] = "";
$ ="Teslimat Tahmini"] = "";
$ ="Teslimat Mesafesi"] = "";
$ ="Teslimat Ücreti"] = "";
$ ="Oylar"] = "";
$ ="Kullanılamaz."] = "";
$ ="Çalışma Saatleri"] = "";
$ ="Şimdi Sipariş Verin"] = "";
$ ="Üzgünüz ama aradığınızı bulamıyoruz."] = "";
$ ="Öğe kimliği gerekli"] = "";
$ ="Kayıt başarılı"] = "";
$ ="İsteğiniz işlenirken bir şeyler ters gitti. Lütfen daha sonra tekrar deneyin."] = "";
$ ="Üzgünüz ama e-posta adresiniz kayıtlarımızda zaten mevcut."] = "";
$ ="Kredi Kartı Başarılı Eklendi"] = "";
$ ="HATA: Kayıt eklenemiyor"] = "";
$ ="Kredi kartı numarası kredi kartı listenizde zaten var"] = "";
$ ="Henüz kredi kartı yok"] = "";
$ ="Giriş Tamam"] = "";
$ ="Giriş Başarısız. Kullanıcı adı veya şifre yanlış"] = "";
$ ="Lütfen sizi paypal'a yönlendirirken bekleyin."] = "";
$ ="Sizi Stripe'a bağlarken lütfen bekleyin."] = "";
$ ="Siparişiniz verilmiştir."] = "";
$ ="HATA: Kayıt eklenemiyor."] = "";
$ ="HATA: Bir şeyler ters gitti"] = "";
$ ="Üzgünüz ama siparişiniz boş"] = "";
$ ="Satıcı Kimliği eksik"] = "";
$ ="Başarılı"] = "";
$ ="Üzgünüz, derecelendirmeniz güncellenirken beyaz bir hata var."] = "";
$ ="Üzgünüm ama derecelendirmeden önce oturum açmanız gerekiyor."] = "";
$ ="Profil"] = "";
$ ="Sipariş Geçmişi"] = "";
$ ="Kredi Kartları"] = "";
$ ="Oturumu Kapat"] = "";
$ ="Kullanıcı oyu kaldırılamaz."] = "";
$ ="Puanlar mevcut değil."] = "";
$ ="Yorumunuz yayınlandı."] = "";
$ ="Üzgünüz, yorum yazmak için giriş yapmanız gerekiyor."] = "";
$ ="Derecelendirilmiş"] = "";
$ ="Henüz inceleme yok."] = "";
$ ="İnceleme içeriği gereklidir."] = "";
$ ="İnceleme içeriği gereklidir."] = "";
$ ="İnceleme Kimliği eksik"] = "";
$ ="İnceleme Kimliği eksik"] = "";
$ ="Yorumunuz güncellendi."] = "";
$ ="HATA: incelemeler güncellenemez."] = "";
$ ="HATA: İncelemeler silinemedi."] = "";
$ ="Satın alma işleminiz gerçekleşti."] = "";
$ ="HATA: Bir veya daha fazla alan eksik."] = "";
$ ="Eksik Sipariş Kimliği"] = "";
$ ="HATA: Oturumunuzun süresi doldu."] = "";
$ ="Hata: Sipariş bulunamadı"] = "";
$ ="Durum kaydedildi."] = "";
$ ="HATA: sipariş güncellenemez."] = "";
$ ="Bu Sipariş size ait değil."] = "";
$ ="YENİ"] = "";
$ ="Hata: Bir şeyler ters gitti, lütfen tekrar deneyin."] = "";
$ ="Eklenebilecek Gıda Öğesi Sayısı 1'den büyük olmalıdır"] = "";
$ ="Paket güncellendi."] = "";
$ ="HATA: Paket bilgisi bulunamadı"] = "";
$ ="Üzgünüz ama bilgilerinizi ekleyemiyoruz. Lütfen daha sonra tekrar deneyin"] = "";
$ ="Üzgünüz ama kullanıcı adınız zaten alınmış."] = "";
$ ="Satıcı zaten aktif."] = "";
$ ="Satıcı Başarıyla etkinleştirildi."] = "";
$ ="Geçersiz Aktivasyon kodu."] = "";
$ ="Üzgünüz ama bilgilerinizi bulamıyoruz."] = "";
$ ="HATA: Eksik parametreler"] = "";
$ ="Kart eklendi."] = "";
$ ="HATA: tüccar bilgisi alınamıyor"] = "";
$ ="Lütfen kredi kartı seçin"] = "";